project_id = "hueccsiuyxjqupxkfhkl"

[functions.upload-docs]
verify_jwt = false

[functions.mediator-chat]
verify_jwt = false

[functions.mediator-openai-direct]
verify_jwt = false

[functions."tools/db_read"]
verify_jwt = true

[functions.transcribe]
verify_jwt = false

[functions.chat]
verify_jwt = false