export const caseCategories = [
  { value: "auto-accident", label: "Auto Accident" },
  { value: "motorcycle-accident", label: "Motorcycle Accident" },
  { value: "commercial-truck-accident", label: "Commercial Truck Accident" },
  { value: "bus-accident", label: "Bus Accident" },
  { value: "bicycle-accident", label: "Bicycle Accident" },
  { value: "pedestrian-accident", label: "Pedestrian Accident" },
  { value: "uber-lyft-rideshare", label: "Uber/Lyft/Rideshare" },
  { value: "boating-maritime-accident", label: "Boating/Maritime Accident" },
  { value: "aviation-accident", label: "Aviation Accident" },
  { value: "train-railroad-accident", label: "Train/Railroad Accident" },
  { value: "workplace-accident", label: "Workplace Accident" },
  { value: "toxic-exposure", label: "Toxic Exposure" },
  { value: "school-daycare-incident", label: "School or Daycare Incident" },
  { value: "sports-recreation-injury", label: "Sports/Recreation Injury" },
  { value: "government-liability", label: "Government Liability" },
  { value: "defamation-libel", label: "Defamation/Libel" },
  { value: "assault-sexual-abuse", label: "Assault/Sexual Abuse" },
  { value: "dog-bite", label: "Dog Bite" },
  { value: "slip-and-fall", label: "Slip and Fall" },
  { value: "trip-and-fall", label: "Trip and Fall" },
  { value: "homeowner-premises", label: "Homeowner Premises" },
  { value: "premises-liability", label: "Premises Liability" },
  { value: "construction-injury", label: "Construction Injury" },
  { value: "product-liability", label: "Product Liability" },
  { value: "medical-malpractice", label: "Medical Malpractice" },
  { value: "nursing-home-neglect", label: "Nursing Home Neglect" },
  { value: "nursing-home-abuse", label: "Nursing Home Abuse" },
  { value: "assault-battery", label: "Assault/Battery" },
  { value: "food-poisoning", label: "Food Poisoning" },
  { value: "wrongful-death", label: "Wrongful Death" },
  { value: "other", label: "Other" }
];